#
# Open Source Android - configuration file
#
# Parameters:
#
# dofX has CAN node ID X
#
# type:
#    TENDON
#    CLASSICAL
#    WHEEL
#
# controller:
#    NOT_USED
#    EPOS2
#    EPOS4
#
# motor:
#    NONE
#    DCX10
#    DCX14
#    DCX16
#    DCX22
#    DCX32
#    RE13
#    RE30
#    ECI40
#    ECI52
#    EC90
#
# inverted:
#    false
#    true
#
# mode: mode of operation selected during initialization: 
#    INTERPOLATED_POSITION_MODE
#    PROFILE_VELOCITY_MODE
#    PROFILE_POSITION_MODE
#    POSITION_MODE
#    VELOCITY_MODE
#    CURRENT_MODE
#    CYCLIC_SYNCHRONOUS_TORQUE_MODE
#
# value: default value that will be sent after EPOS board initialization, according to the selected mode of operation
# 

robot:
  name: 'HighSpeedAndroid_legs'
  dof: 10  # Number of Degrees Of Freedom.
  can_device: 'can0'

#Waist
dof1: {name: 'waist', type: 'CLASSICAL', node_id: 1, controller: 'EPOS4', motor: 'EC90', inverted: false, mode: 'PROFILE_POSITION_MODE', value: 0}

#Pelvis
dof2: {name: 'pelvis', type: 'CLASSICAL', node_id: 2, controller: 'EPOS4', motor: 'EC90', inverted: false, mode: 'PROFILE_POSITION_MODE', value: 0}

#Right leg
dof4: {name: 'right_leg/hip', type: 'CLASSICAL', node_id: 4, controller: 'EPOS4', motor: 'EC90', inverted: true, mode: 'PROFILE_POSITION_MODE', value: 0}
dof6: {name: 'right_leg/knee', type: 'CLASSICAL', node_id: 6, controller: 'EPOS4', motor: 'EC90', inverted: false, mode: 'PROFILE_POSITION_MODE', value: 0}
dof8: {name: 'right_leg/ankle', type: 'CLASSICAL', node_id: 8, controller: 'EPOS4', motor: 'DCX32', inverted: false, mode: 'PROFILE_POSITION_MODE', value: 0}
dof10: {name: 'right_leg/drive', type: 'WHEEL', node_id: 10, controller: 'EPOS4', motor: 'EC90', inverted: true, mode: 'PROFILE_POSITION_MODE', value: 0}

#Left leg
dof3: {name: 'left_leg/hip', type: 'CLASSICAL', node_id: 3, controller: 'EPOS4', motor: 'EC90', inverted: false, mode: 'PROFILE_POSITION_MODE', value: 0}
dof5: {name: 'left_leg/knee', type: 'CLASSICAL', node_id: 5, controller: 'EPOS4', motor: 'EC90', inverted: true, mode: 'PROFILE_POSITION_MODE', value: 0}
dof7: {name: 'left_leg/ankle', type: 'CLASSICAL', node_id: 7, controller: 'EPOS4', motor: 'DCX32', inverted: true, mode: 'PROFILE_POSITION_MODE', value: 0}
dof9: {name: 'left_leg/drive', type: 'WHEEL', node_id: 9, controller: 'EPOS4', motor: 'EC90', inverted: false, mode: 'PROFILE_POSITION_MODE', value: 0}
