# struct syntax
nodes:
  node1:
    id: 1
    name: right_weel
    eds_pkg: osa_communication # optionals package  name for relative path
    eds_file: "config/epos2-re13.dcf" # path to EDS/DCF file
  node2:
    id: 2
    name: left_wheel
    eds_pkg: osa_communication # optionals package  name for relative path
    eds_file: "config/epos2-re13.dcf" # path to EDS/DCF file

#defaults: # optional, all defaults can be overwritten per node
#  eds_pkg: my_config_package # optional package  name for relative path
#  eds_file: "my_config.dcf" # path to EDS/DCF file
#  dcf_overlay: # "ObjectID": "ParameterValue" (both as strings)
#    "1016sub1" : "0x7F0064" # heartbeat timeout of 100 ms for master at 127
#    "1017": "100" # heartbeat producer
 # canopen_chain_node settings ..
   motor_allocator: canopen::Motor402::Allocator # select allocator for motor layer
   motor_layer: settings passed to motor layer (plugin-specific)
   switching_state: 5 # (Operation_Enable), state for mode switching
   pos_to_device: "rint(rad2deg(pos)*1000)" # rad -> mdeg
   pos_from_device: "deg2rad(obj6064)/1000" # actual position [mdeg] -> rad
   vel_to_device: "rint(rad2deg(vel)*1000)" # rad/s -> mdeg/s
   vel_from_device: "deg2rad(obj606C)/1000" # actual velocity [mdeg/s] -> rad/s
   eff_to_device: "rint(eff)" # just round to integer
   eff_from_device: "0" # unset
