defaults: # optional, all defaults can be overwritten per node
  publish: ["1001"] # list of objects to be published (one topic per node)
nodes:
  node1:
    # ...
    publish: ["1003sub0!"] # list of objects to be published (one topic per node)
  node2:
    # ...
